language: crystal

services:
  - docker
  - postgresql

before_script:
  - psql -c 'create database runners_plaza_test;' -U postgres

script:
  - crystal tool format --check
  - bin/ameba
  - crystal spec
  - docker-compose build
